sudo: false
language: node_js
node_js:
 - "node"
 - "iojs"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

before_script:
  - npm install -g gulp spacejam

script:
  - gulp
  - spacejam test-packages ./

